#!/bin/sh
# This script is only used for developement. It is removed by the 
# distribution process. 


set -e

OCAMLBUILD=${OCAMLBUILD:="ocamlbuild -tag debug -classic-display \
                          -use-ocamlfind"}

action () 
{
    case $1 in
      default)      $OCAMLBUILD vg.cmx vgr_pdf.cmx vgr_svg.cmx vgr_htmlc.cmx vgr_cairo2.cmx ;;
      tests)        $OCAMLBUILD rpdf.native rsvg.native; action rhtmlc ;;
      rhtmlc)       shift; 
                    pkg/db-locs
                    jsoo-build $* test/rhtmlc.ml
                    ;;
      sqc)          shift; jsoo-build $* test/sqc.ml ;;
      min_htmlc)    shift; jsoo-build $* test/min_htmlc.ml ;;
      doc)          shift; pkg-doc $* doc/dev-api.docdir ;;
      api-doc)      shift; pkg-doc $* doc/api.docdir ;;
      clean)        $OCAMLBUILD -clean ;;
      jsoo)         shift; jsoo-build $* ;;
      *)            $OCAMLBUILD $* ;;
    esac
} 

if [ $# -eq 0 ]; 
then action default ; 
else action $*; fi
