#!/bin/sh
# This script is only used for developement. It is removed by the 
# distribution process. 

set -e

OCAMLBUILD=${OCAMLBUILD:="ocamlbuild -classic-display -use-ocamlfind"}

action () 
{
    case $1 in
      default)      $OCAMLBUILD vg.cmx vgr_pdf.cmx vgr_svg.cmx vgr_htmlc.cmx ;;
      tests)        $OCAMLBUILD rpdf.native rsvg.native; action rhtmlc ;;
      rhtmlc)       shift; devel/jsoo-build $* test/rhtmlc.ml ;;
      doc)          shift; devel/pkg-doc $* doc/dev-api.docdir ;;
      distrib)      devel/pkg-distrib ;;
      publish)      devel/pkg-www ;;
      publish-opam) devel/pkg-opam ;;
      clean)        $OCAMLBUILD -clean ;;
      jsoo)         shift; devel/jsoo-build $* ;;
      *)            $OCAMLBUILD $* ;;
    esac
} 

if [ $# -eq 0 ]; 
then action default ; 
else action $*; fi
