#!/bin/sh

# Usage: pkg-distrib 
# Make a distribution tarball in /tmp.

set -xev
LOC=`dirname $0`

TAR=${TAR="tar"}

. $LOC/pkg-info

rm -R -f $CLONEDIR
#git clone -b master . $CLONEDIR
cp -R . $CLONEDIR
cd $CLONEDIR

# Substitute a few things
. $LOC/pkg-varsubsts

# Remove dev artefacts
rm -R -f .git .gitignore $DEV_BUILD_ARTEFACTS

if [ -f $LOC/pkg-oasis-hook ]; then
    . $LOC/pkg-oasis-hook
fi

# Generate oasis artefacts
oasis setup

# Test oasis setup 
ocaml setup.ml -configure
ocaml setup.ml -build

# Generate static API doc 
. $LOC/pkg-doc -no-links -I src doc/api.docdir
cp _build/doc/api.docdir/*.html doc/

# Invoke hook
if [ -f $LOC/pkg-distrib-hook ]; then
    . $LOC/pkg-distrib-hook
fi

# Clean and wrap up the project
ocaml setup.ml -distclean

cd ..
$TAR -cvjf $PKGDIR.tbz $PKGDIR
rm -R $PKGDIR


