#!/bin/sh

# Usage: pkg-info
# Retrieves meta data about the package and store it in variables for
# other scripts to use.

set -e
LOC=`dirname $0`

ECHO=${ECHO:="echo"}
SED=${SED:="sed"}
TR=${TR:="tr"}
OASISQ=${OASISQ:="oasis query"}

VERSION=`$ECHO "\`git describe master\`" | $SED "s/^.\(.*\)/\1/"`
NAME=`$OASISQ Name`
MODNAME=`$OASISQ Library\("$NAME"\).Modules`
SYNOPSIS=`$OASISQ Synopsis`
RAWDESCRIPTION=`$OASISQ Description`
DESCRIPTION=`$OASISQ Description | $SED "s|$|\\\\\|"`
HOMEPAGE=`$OASISQ Homepage`
MAINTAINER=`$OASISQ Maintainers`
AUTHORS=`$OASISQ Authors`
OCAMLVERSION=`$OASISQ OCamlVersion`
DEPS=`$OASISQ "Library(\"$NAME\").BuildDepends"`
GITREPO=`$OASISQ "SrcRepo(head).Location"`
if [ "$DEPS" ]; then
 PPDEPS=`$ECHO ", $DEPS"| $SED "s|,|,   |g" | $TR "," "\n" | $SED "s|$|\\\\\|"`
fi

PKGDIR=$NAME-$VERSION
WWWROOT=${WWWROOT:="$HOME/sync/erratique"}
PKGWWWROOT=${PKGWWWROOT:="$WWWROOT/maps/software/$NAME"}
OPAMWWWROOT=${OPAMWWWROOT:="$WWWROOT/maps/opam"}

BUILDDIR=${BUILDDIR:="_build"}
CLONEDIR=${CLONEDIR:="/tmp/$PKGDIR"}
DEV_BUILD_ARTEFACTS="_tags myocamlbuild.ml"

if [ -f $LOC/pkg-info-hook ]; then
    . $LOC/pkg-info-hook
fi
