#!/bin/sh

## Usage: pkg-opam-git
## Prepare build system for an opam git package.

OASIS=${OASIS:="oasis"}

set -e
LOC=`dirname $0`

. $LOC/pkg-info

# Substitute a few things
ROOTDIR=.
. $LOC/pkg-varsubsts

# Remove dev artefacts
rm -f $DEV_BUILD_ARTEFACTS

if [ -f $LOC/pkg-opam-git-hook ]; then
    . $LOC/pkg-opam-git-hook
fi

if [ -f $LOC/pkg-oasis-hook ]; then
    . $LOC/pkg-oasis-hook
fi

# Generate oasis artefacts
$OASIS setup

