#!/bin/sh

# Usage: pkg-varsubst
# The variable $ROOTDIR should be set

set -e
LOC=`dirname $0`

SED=${SED="sed"}

VARSUBSTS="s|%%NAME%%|$NAME|g; \
           s|%%MODNAME%%|$MODNAME|g; \
           s|%%VERSION%%|$VERSION|g; \
           s|%%SYNOPSIS%%|$SYNOPSIS|g; \
           s|%%DESCRIPTION%%|$DESCRIPTION |g; \
           s|%%HOMEPAGE%%|$HOMEPAGE|g; \
           s|%%MAINTAINER%%|$MAINTAINER|g; \
           s|%%AUTHORS%%|$AUTHORS|g; \
           s|%%OCAMLVERSION%%|$OCAMLVERSION|g; \
           s|%%DEPS%%|$DEPS|g; \
           s|%%PPDEPS%%|$PPDEPS |g;" 

if [ -f $LOC/pkg-varsubsts-hook ]; then
    . $LOC/pkg-varsubsts-hook
fi

for file in `git ls-files`; do
    if [ ! -x "$file" ]; then                # skip scripts
        $SED "$VARSUBSTS" $file > $file.tmp
        mv -f $file.tmp $file
    fi
done
