#!/bin/sh

# Usage: build has_native has_jsoo

set -e 
LOC=`dirname $0`

. $LOC/pkg-builder

NATIVE=$1
JSOO=$2

add lib pkg/META		
add lib src/vgr_pdf.mli	
add lib src/vgr_pdf.cmi
add lib src/vgr_pdf.cmx	
add lib src/vgr_svg.mli
add lib src/vgr_svg.cmi
add lib src/vgr_svg.cmx
add lib src/vg.mli	
add lib src/vg.cmi
add lib src/vg.cmx
add lib src/vg.cma
add lib src/vg.a
add lib src/vg.cmxa
add lib src/vg.cmxs

if [ "$JSOO" == "true" ]; then 
    add lib src/vgr_htmlc.mli	
    add lib src/vgr_htmlc.cmx 
    add lib src/vgr_htmlc.cmi
    add lib src/vg_htmlc.cma
    add lib src/vg_htmlc.a
    add lib src/vg_htmlc.cmxa
    add lib src/vg_htmlc.cmxs
fi

add doc README.md
add doc CHANGES.md

build
install vg
