#!/bin/sh

# Usage: pkg-www-release
# Publishes the project on the www with webglue

set -e
LOC=`dirname $0`

. $LOC/pkg-info

TAR=${TAR:="tar"}
CP=${CP:="cp"}
RM=${RM:="rm"}
WEBGLUE=${WEBGLUE:="webglue"}

ARCHIVE=/tmp/$PKGDIR.tbz

# Add the release tarball 
cp $ARCHIVE $PKGWWWROOT/releases/

# Update the doc
rm -R $PGKWWWROOT/doc
$TAR -C $PKGWWWROOT --strip-components=1 -xvjf $ARCHIVE $PKGDIR/doc

# Update the webpage
cd $WWWROOT
echo "$VERSION" | $WEBGLUE set --replace $NAME s-last-version
$WEBGLUE get timestamp utc | $WEBGLUE set --replace $NAME s-updated

if [ -f $LOC/pkg-www-release-hook ]; then
    . $LOC/pkg-www-release-hook
fi
