#!/bin/sh

# Usage: pkg-distrib 
# Make a distribution tarball in /tmp.

set -e
LOC=`dirname $0`

. $LOC/pkg-info

TAR=${TAR:="tar"}

rm -R -f $CLONEDIR
git clone -b master . $CLONEDIR
cd $CLONEDIR

# Substitute a few things
. $LOC/pkg-varsubsts

# Remove dev artefacts
rm -R -f .git .gitignore $DEV_BUILD_ARTEFACTS

# Generate static API doc 
. $LOC/pkg-doc -no-links -I src doc/api.docdir
cp _build/doc/api.docdir/*.html doc/

# Invoke hook
if [ -f $LOC/pkg-distrib-hook ]; then
    . $LOC/pkg-distrib-hook
fi

cd ..
$TAR -cvjf $PKGDIR.tbz $PKGDIR
rm -R $PKGDIR
