#!/bin/sh

# Usage: pkg-distrib 
# Make a distribution tarball in /tmp.

set -e
LOC=`dirname $0`

. $LOC/config

PKGDIR=$NAME-$VERSION
CLONEDIR=${CLONEDIR:="/tmp/$PKGDIR"}

OCAMLBUILD=${OCAMLBUILD:="ocamlbuild -classic-display -use-ocamlfind"}
TAR=${TAR:="tar"}

# Start from a checkout of master
rm -R -f $CLONEDIR
git clone -b master . $CLONEDIR
cd $CLONEDIR

# Substitute a few things
. $LOC/pkg-varsubsts

# Remove dev artefacts
rm -R -f .git .gitignore build $DEV_BUILD_ARTEFACTS

# Generate static API doc (if any)
if [ -f doc/api.odocl ]; then 
  . $LOC/pkg-doc doc/api.docdir
  cp _build/doc/api.docdir/*.html doc/
fi

# Invoke hook
if [ -f $LOC/hook-pkg-distrib ]; then
    . $LOC/hook-pkg-distrib
fi

# Cleanup any mess
$OCAMLBUILD -clean

# Make tarball
cd ..
$TAR -cvjf $PKGDIR.tbz $PKGDIR
rm -R $PKGDIR
