#!/bin/sh

# Usage: pkg-distrib 
# Make a distribution tarball in /tmp.

set -e
LOC=`dirname $0`

. $LOC/pkg-info

OCAMLBUILD=${OCAMLBUILD:="ocamlbuild -classic-display -use-ocamlfind"}
TAR=${TAR:="tar"}

rm -R -f $CLONEDIR
git clone -b master . $CLONEDIR
cd $CLONEDIR

# Substitute a few things
. $LOC/pkg-varsubsts

# Remove dev artefacts
rm -R -f .git .gitignore $DEV_BUILD_ARTEFACTS

# Generate static API doc 
. $LOC/pkg-doc -no-links -I src doc/api.docdir
cp _build/doc/api.docdir/*.html doc/

$OCAMLBUILD -clean

# Invoke hook
if [ -f $LOC/hook-pkg-distrib ]; then
    . $LOC/hook-pkg-distrib
fi

cd ..
$TAR -cvjf $PKGDIR.tbz $PKGDIR
rm -R $PKGDIR
