#!/bin/sh

# Usage: pkg-www-doc
# Publishes the project's docs on the www

set -e
LOC=`dirname $0`

. $LOC/pkg-info

rm -R -f $CLONEDIR
git clone -b master . $CLONEDIR
cd $CLONEDIR

. $LOC/pkg-varsubsts

if [ -f doc/api.docdir ]; then 
  ./devel/pkg-doc doc/api.docdir
fi

if [ -f $LOC/pkg-www-doc-hook ]; then
    . $LOC/pkg-www-doc-hook
fi

if [ -f doc/api.docdir ]; then
  cp $BUILDDIR/doc/api.docdir/* $PKGWWWROOT/doc/
fi
