#!/bin/sh

## Usage: pkg-opam-git
## Prepare build system for an opam git package.

set -e
LOC=`dirname $0`

. $LOC/pkg-info
. $LOC/pkg-varsubsts

if [ -f $LOC/pkg-opam-git-hook ]; then
    . $LOC/pkg-opam-git-hook
fi
