#!/bin/sh

## Usage: pkg-git
## Prepare package for an opam git/pinned package.

set -e
LOC=`dirname $0`

. $LOC/config
. $LOC/pkg-varsubsts

if [ -f $LOC/hook-pkg-git ]; then
    . $LOC/hook-pkg-git
fi
