#!/bin/sh

# Usage: pkg-info
# Retrieves meta data about the package and store it in variables for
# other scripts to use.

set -e
LOC=`dirname $0`

. $LOC/config

PKGDIR=$NAME-$VERSION
BUILDDIR=${BUILDDIR:="_build"}
CLONEDIR=${CLONEDIR:="/tmp/$PKGDIR"}
DEV_BUILD_ARTEFACTS=${DEV_BUILD_ARTEFACTS:=""}

if [ -f $LOC/hook-pkg-info ]; then
    . $LOC/hook-pkg-info
fi
