#!/bin/sh

# Usage: pkg-www-demos
# Publishes the project's demos on the www

set -e
LOC=`dirname $0`

. $LOC/pkg-info

rm -R -f $CLONEDIR
git clone -b master . $CLONEDIR
cd $CLONEDIR

. $LOC/pkg-varsubsts

for D in $PKGDEMOS; do
    ./build $D
    cp $BUILDDIR/test/$D.{html,js} $PKGWWWROOT/demos/
done

